set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN E3} [get_ports {clk}]

set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN F4} [get_ports {ps2_clk}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN B2} [get_ports {ps2_dat}]

set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN J17} [get_ports {AN[0]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN J18} [get_ports {AN[1]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN T9} [get_ports {AN[2]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN J14} [get_ports {AN[3]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN P14} [get_ports {AN[4]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN T14} [get_ports {AN[5]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN K2} [get_ports {AN[6]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN U13} [get_ports {AN[7]}]

set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN T10} [get_ports {SEG[0]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN R10} [get_ports {SEG[1]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN K16} [get_ports {SEG[2]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN K13} [get_ports {SEG[3]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN P15} [get_ports {SEG[4]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN T11} [get_ports {SEG[5]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN L18} [get_ports {SEG[6]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN H15} [get_ports {SEG[7]}]

set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN N17} [get_ports {btn_c}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN M18} [get_ports {btn_u}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN P18} [get_ports {btn_d}]

set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN J15} [get_ports {SW[0]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN L16} [get_ports {SW[1]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN M13} [get_ports {SW[2]}]
set_property -dict {IOSTANDARD LVCMOS33     PACKAGE_PIN R15} [get_ports {SW[3]}]