@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 13 14:46:24 +0300 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim test_behav -key {Behavioral:sim_1:Functional:test} -tclbatch test.tcl -view M:/2010/IVBO-01-20/Ermishin/S2_L2/S2_L1.srcs/sim_1/imports/S2_Lab_1/testbench_behav.wcfg -log simulate.log"
call xsim  test_behav -key {Behavioral:sim_1:Functional:test} -tclbatch test.tcl -view M:/2010/IVBO-01-20/Ermishin/S2_L2/S2_L1.srcs/sim_1/imports/S2_Lab_1/testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
